version: "3.7"

# environment
x-volumes: &env-volume
  ALLOWED_HOSTS: "http://localhost:8080,http://localhost"
  SECRET_KEY: "uwqr823y98ruwhnsenjfuchrbgyu2oriqwnefueiyucnewc"

  MONGO_HOST: "mongodb://root:password@db:27017/?authSource=admin"
  MONGO_DB_NAME: "blog_db"
  REDIS_LOCAL_URL: "redis://redis:6379/1"

  FIREBASE_ACCOUNT_CREDENTIAL_PATH: "firebase-credentials.json"


services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: nayan32biswas/fastapi_blog:latest
    container_name: fastapi_blog_server
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - 8000:8000
    environment:
      <<: *env-volume
    volumes:
      - ./:/app/server/
    depends_on:
      - db
      - redis
    networks:
      - fastapi_blog-backend-tier

  db:
    image: mongo
    # restart: always
    container_name: fastapi_blog_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - fastapi_blog-db:/data/db
    networks:
      - fastapi_blog-backend-tier

  redis:
    image: redis:6
    container_name: fastapi_blog_redis
    # restart: unless-stopped
    networks:
      - fastapi_blog-backend-tier
    volumes:
      - fastapi_blog-redis:/data

volumes:
  fastapi_blog-db:
    driver: local
  fastapi_blog-redis:
    driver: local

networks:
  fastapi_blog-backend-tier:
    driver: bridge
